---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: hermes-role
rules:
- apiGroups:
  - hermes.pml.com
  resources:
  - subscriberrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hermes.pml.com
  resources:
  - subscriberrules/finalizers
  verbs:
  - update
- apiGroups:
  - hermes.pml.com
  resources:
  - subscriberrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
