# permissions for end users to edit subscriberrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscriberrule-editor-role
rules:
- apiGroups:
  - hermes.pml.com
  resources:
  - subscriberrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hermes.pml.com
  resources:
  - subscriberrules/status
  verbs:
  - get
