// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Hermesen string `form:"hermesen"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type HermesReq struct {
	Url string `form:"url"`
}

type HermesResp struct {
	Hermesen string `json:"hermesen"`
}
