// Code generated by goctl. DO NOT EDIT.
package types

import "github.com/prometheus/alertmanager/template"

type KV map[string]string

type ExpandReq struct {
	Hermesen string `form:"hermesen"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type HermesReq struct {
	Url string `form:"url"`
	GroupLabels KV `json:"groupLabels"`
	Alerts   template.Alerts `json:"alerts"`
}

type HermesResp struct {
	Hermesen string `json:"hermesen"`
}
