apiVersion: hermes.pml.com/v1
kind: SubscriberRule
metadata:
 name: computer-metrics-subscribe
spec:
 subscribeType: SubsCondition
 subscriberAddress: "http://ip+port/receiver"
 realTimeMetricList:
   - jin
   - xin
 prometheusRule:
  groups:
   - name: test-demo.rules
     rules:
      - alert: TestAlert
        annotations:
         aggerateRules: 100 * (count(up == 0) BY (job, namespace, service) / count(up)
          BY (job, namespace, service)) > 10
         receiverAddress: http://10.0.0.1:9876
         returnValueFlag: "false"
        expr: 100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job,
         namespace, service)) > 10
        labels:
         alertlabel: testalert