apiVersion: hermes.pml.com/v1
kind: SubscriberRule
metadata:
 name: computer-metrics-subscribe
spec:
 subscribeType: SubsCondition
 subscriberAddress: "http://ip+port/receiver"
 realTimeMetricList:
   - jin
   - xin
 prometheusRule:
  groups:
   - name: test-demo.rules
     rules:
      - alert: TestAlert
        annotations:
         aggerateRules: 100 * (count(up == 0) BY (job, namespace, service) / count(up)
          BY (job, namespace, service)) > 10
         receiverAddress: http://10.0.0.1:9876
         returnValueFlag: "false"
        expr: 100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job,
         namespace, service)) > 10
        labels:
         alertlabel: testalert

---
apiVersion: hermes.pml.com/v1
kind: SubscriberRule
metadata:
  name: computer-metrics-subscribe1
spec:
  subscribeType: SubsRealTime
  subscriberAddress: "http://127.0.0.1:5001/realtimereceiver"
  realTimeMetricList:
    - system_memory_usage
    - system_cpu_time
---
apiVersion: hermes.pml.com/v1
kind: SubscriberRule
metadata:
  name: test-qps
  namespace: hypermonitor
spec:
  prometheusRule:
    groups:
      - name: serverless.rules.case4-component1-5.test1
        rules:
          - alert: test-qps.rules
            annotations:
              aggerateRules: rate(io_sid_traffics{component_id=""}[30s]) > bool 0 > 0
              receiverAddress: http://192.168.101.47:5000/receiver
              returnValueFlag: "true"
            expr: rate(io_sid_traffics{component_id=""}[30s]) > bool 0 > 0
            for: 1s
            labels:
              alertlabel: test
              severity: critical
  subscribeType: SubsCondition
  subscriberAddress: http://192.168.101.47:5000/receiver