apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-conf
  namespace: hypermonitor
  labels:
    app: hermes
    component: hermes
data:
  hermes-config: |
    Name: hermes-api
    Host: 0.0.0.0
    Port: 8888
    Transform:
      Etcd:
        Hosts:
          - 192.168.2.62:2379
        Key: transform.rpc
