apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hypermonitor
  labels:
    app: hermes
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - args:
            - /app/hermes
            - --metrics-bind-address=:8897
            - --health-probe-bind-address=:8898
          name: hermes
          image: 172.17.21.119:30080/library/hermes:v0.1.0_0520_1
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]
          ports:
            - containerPort: 8897
            - containerPort: 8898
            - containerPort: 8899
          readinessProbe:
            tcpSocket:
              port: 8899
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8899
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 2000m
              memory: 2048Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: hermes-config-vol
              mountPath: /conf
      hostNetwork: true
      serviceAccount: hermes-manager
      serviceAccountName: hermes-manager
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - configMap:
            name: hermes-conf
            items:
              - key: hermes-config
                path: hermes-conf.yaml
          name: hermes-config-vol
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-svc
  namespace: hypermonitor
spec:
  ports:
    - nodePort: 31447
      name: hermes
      port: 8899
      protocol: TCP
      targetPort: 8899
    - nodePort: 31451
      name: metrics
      port: 8897
      protocol: TCP
      targetPort: 8897
    - nodePort: 31452
      port: 8898
      name: health
      protocol: TCP
      targetPort: 8898
  type: NodePort
  selector:
    app: hermes
