// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package server

import (
	"context"

	"Hermes/rpc/transform/internal/logic"
	"Hermes/rpc/transform/internal/svc"
	"Hermes/rpc/transform/pb/transform"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Expand(ctx context.Context, in *transform.ExpandReq) (*transform.ExpandResp, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}

func (s *TransformerServer) Hermesen(ctx context.Context, in *transform.HermesenReq) (*transform.HermesResp, error) {
	l := logic.NewHermesenLogic(ctx, s.svcCtx)
	return l.Hermesen(in)
}
