// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	hermesdFieldNames          = builder.RawFieldNames(&Hermesd{})
	hermesdRows                = strings.Join(hermesdFieldNames, ",")
	hermesdRowsExpectAutoSet   = strings.Join(stringx.Remove(hermesdFieldNames, "`create_time`", "`update_time`"), ",")
	hermesdRowsWithPlaceHolder = strings.Join(stringx.Remove(hermesdFieldNames, "`hermes`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheHermesdHermesPrefix = "cache:hermesd:hermes:"
)

type (
	hermesdModel interface {
		Insert(ctx context.Context, data *Hermesd) (sql.Result, error)
		FindOne(ctx context.Context, hermes string) (*Hermesd, error)
		Update(ctx context.Context, data *Hermesd) error
		Delete(ctx context.Context, hermes string) error
	}

	defaultHermesdModel struct {
		sqlc.CachedConn
		table string
	}

	Hermesd struct {
		Hermes string `db:"hermes"` // shorten key
		Url    string `db:"url"`    // original url
	}
)

func newHermesdModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultHermesdModel {
	return &defaultHermesdModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`hermesd`",
	}
}

func (m *defaultHermesdModel) Insert(ctx context.Context, data *Hermesd) (sql.Result, error) {
	hermesdHermesKey := fmt.Sprintf("%s%v", cacheHermesdHermesPrefix, data.Hermes)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, hermesdRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Hermes, data.Url)
	}, hermesdHermesKey)
	return ret, err
}

func (m *defaultHermesdModel) FindOne(ctx context.Context, hermes string) (*Hermesd, error) {
	hermesdHermesKey := fmt.Sprintf("%s%v", cacheHermesdHermesPrefix, hermes)
	var resp Hermesd
	err := m.QueryRowCtx(ctx, &resp, hermesdHermesKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `hermes` = ? limit 1", hermesdRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, hermes)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHermesdModel) Update(ctx context.Context, data *Hermesd) error {
	hermesdHermesKey := fmt.Sprintf("%s%v", cacheHermesdHermesPrefix, data.Hermes)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `hermes` = ?", m.table, hermesdRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Url, data.Hermes)
	}, hermesdHermesKey)
	return err
}

func (m *defaultHermesdModel) Delete(ctx context.Context, hermes string) error {
	hermesdHermesKey := fmt.Sprintf("%s%v", cacheHermesdHermesPrefix, hermes)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `hermes` = ?", m.table)
		return conn.ExecCtx(ctx, query, hermes)
	}, hermesdHermesKey)
	return err
}

func (m *defaultHermesdModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheHermesdHermesPrefix, primary)
}

func (m *defaultHermesdModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `hermes` = ? limit 1", hermesdRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultHermesdModel) tableName() string {
	return m.table
}
