// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package transformer

import (
	"context"

	"github.com/Hermes/rpc/transform/transform"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExpandReq   = transform.ExpandReq
	ExpandResp  = transform.ExpandResp
	HermesResp  = transform.HermesResp
	HermesenReq = transform.HermesenReq

	Transformer interface {
		Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error)
		Hermesen(ctx context.Context, in *HermesenReq, opts ...grpc.CallOption) (*HermesResp, error)
	}

	defaultTransformer struct {
		cli zrpc.Client
	}
)

func NewTransformer(cli zrpc.Client) Transformer {
	return &defaultTransformer{
		cli: cli,
	}
}

func (m *defaultTransformer) Expand(ctx context.Context, in *ExpandReq, opts ...grpc.CallOption) (*ExpandResp, error) {
	client := transform.NewTransformerClient(m.cli.Conn())
	return client.Expand(ctx, in, opts...)
}

func (m *defaultTransformer) Hermesen(ctx context.Context, in *HermesenReq, opts ...grpc.CallOption) (*HermesResp, error) {
	client := transform.NewTransformerClient(m.cli.Conn())
	return client.Hermesen(ctx, in, opts...)
}
